### ISSUE TITLE
脚本可以运行但是连接主机的时候会报错

### ISSUE THREAD

**Issue by wszme** [lvht/btk#25]
```
       def RequestPasskey(self, device):
        print("RequestPasskey (%s)" % (device))
        passkey = ""
        kb = ev.InputDevice(glob.glob('/dev/input/by-path/*event-kbd')[0])
        print(kb)
        print("connecting")
        passkey = input("Tell me your pin")
        print(passkey)
        # for event in kb.readoop():
        #     data = ev.categorize(event)  #ev 来自相关设备和键盘的事件
        #     if event.type != ev.ecodes.EV_KEY:
        #         continue
        #     elif data.keystate == 0: # ignore keyup
        #         continue
        # 
        #     key = ev.ecodes.KEY[event.code][4:]
        #     if key == 'ENTER': # we are done
        #         break
        #     elif key in ['1','2','3','4','5','6','7','8','9','0']:
        #         passkey = passkey + key

        set_trusted(device)
        return int(passkey)
```

注释的地方报错了，还有两个包两个包没有装上（GLib, Gio）上面是我的解决方案；
然后我就用input方法替换取pin码的操作，可以连接成功，能够连接上设备了，但是接下来也不能实现按键和鼠标的操作，不知道是为什么，请求帮助，在线急等，求回复，谢谢，求联系方式。
希望能够帮助我万分感谢。
 这里是我的环境
  BlueZ(>=5)这个没有找到没有装（我现在正在准备找这个然后开始安装这个）再次期待能联系我
- python==3.6
- [PyGObject] ==3.26.1
- [evdev] ==1.3.0
- [pydbus]==0.6.0
- [PyBlueZ] ==0.23
一下是报错信息
device /dev/input/by-path/platform-i8042-serio-0-event-kbd, name "AT Translated Set 2 keyboard", phys "isa0060/serio0/input0"
Traceback (most recent call last):
  File "/home/b0g3/桌面/bluetest/dbus.py", line 43, in on_method_call
    result = getattr(self, method_name)(*args)
  File "/home/b0g3/桌面/bluetest/agent.py", line 83, in RequestPasskey
    for event in kb.readoop():
AttributeError: 'InputDevice' object has no attribute 'readoop'

**Comment by taoso** [comment]
代码里是 `kb.read_loop()` 吧，你是最新代码吗？还是自己改过了？

```python
def RequestPasskey(self, device):
        print("RequestPasskey (%s)" % (device))
        passkey = ""
        kb = ev.InputDevice(glob.glob('/dev/input/by-path/*event-kbd')[0])
        print(kb)
        for event in kb.read_loop():
            data = ev.categorize(event)
```

另外 PyGObject 需要使用系统包管理器安装，pip 是装不了的，不同的发行版名字也各不相同，可以参考[这里](https://pygobject.readthedocs.io/en/latest/getting_started.html)。

我后来转用 mac，没有了实验环境，也就没怎么动这个项目了。

**Comment by wszme** [comment]
非常感谢能够回复我
最新的代码，不是我自己的，我自己的就加了一个input的函数把下面for给注释掉了，因为会kb对象找不到inputdevice；
我们可以加一个WeChat吗？
我的号是sunyiyoo



---原始邮件---
发件人: "lvht"<notifications@github.com&gt;
发送时间: 2020年4月20日(星期一) 上午10:27
收件人: "lvht/btk"<btk@noreply.github.com&gt;;
抄送: "wszme"<896795262@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [lvht/btk] 脚本可以运行但是连接主机的时候会报错 (#25)




 
代码里是 kb.read_loop() 吧，你是最新代码吗？还是自己改过了？
 def RequestPasskey(self, device):         print("RequestPasskey (%s)" % (device))         passkey = ""         kb = ev.InputDevice(glob.glob('/dev/input/by-path/*event-kbd')[0])         print(kb)         for event in kb.read_loop():             data = ev.categorize(event)
 
另外 PyGObject 需要使用系统包管理器安装，pip 是装不了的，不同的发行版名字也各不相同，你需要自己 google 一下。
 
我后来转用 mac，没有了实验环境，也就没怎么动这个项目了。
